CATEGORY_OTHER: int

HAP_PERMISSION_READ: str

HAP_REPR_AID: str
HAP_REPR_CHARS: str
HAP_REPR_FORMAT: str
HAP_REPR_IID: str
HAP_REPR_MAX_LEN: str
HAP_REPR_PERM: str
HAP_REPR_PRIMARY: str
HAP_REPR_SERVICES: str
HAP_REPR_TYPE: str
HAP_REPR_VALID_VALUES: str
HAP_REPR_VALUE: str